{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.0.2.jar",
          "url": "builder-7.0.2.jar",
          "size": 6472933,
          "sha512": "23905e0eea705d6d9a61ca3a667b4d9034645a527540f564dee77bf14a51cc2d1dc6fccb5910ea8fe247c3590918eed36514ea90c7c33cf0bb2912010c04d282",
          "sha256": "6bcf114a903c80f4723276be31ba95f752b5d5cc4f6d36f86bd8b89041c48fc0",
          "sha1": "f46bbc890dfaea9af0c74da1a59039f024ac7a04",
          "md5": "04f34eb59db21d5f59f0a47d132f61cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-7.0.2.jar",
          "url": "builder-7.0.2.jar",
          "size": 6472933,
          "sha512": "23905e0eea705d6d9a61ca3a667b4d9034645a527540f564dee77bf14a51cc2d1dc6fccb5910ea8fe247c3590918eed36514ea90c7c33cf0bb2912010c04d282",
          "sha256": "6bcf114a903c80f4723276be31ba95f752b5d5cc4f6d36f86bd8b89041c48fc0",
          "sha1": "f46bbc890dfaea9af0c74da1a59039f024ac7a04",
          "md5": "04f34eb59db21d5f59f0a47d132f61cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.0.2-javadoc.jar",
          "url": "builder-7.0.2-javadoc.jar",
          "size": 723866,
          "sha512": "230c8219edb616bc14957e81f338221c1f39e091eb53f14d87c402b6a56de6d7a3076bd851708adc9553dae7fe889bee089f95ba5e2f9fa1eadbaa38b1ee1f40",
          "sha256": "c8846942d37b3469ccc820fe97a01f8c31496f196d92d3450d0ea443804c317d",
          "sha1": "c98fe5d6c5861f53cb5d4302d0a06dd472847fc5",
          "md5": "233ce598fc44e1ddeb51b619ed209f96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-7.0.2-sources.jar",
          "url": "builder-7.0.2-sources.jar",
          "size": 279435,
          "sha512": "9fddb542486f7a15646224ae91730335b2cae730254d76e91010b96173b199f6a8778fc9eb1ee534cc007e5005d12d5176fbe26f0f58fb3473d0fce771b4dbe6",
          "sha256": "863c21e2af10dda4881dbeb8ac5210a2b8fb12ab8e3480fb636c8ec38e302bc2",
          "sha1": "81cc444ffb1f950548d4761cfd21f8f7a3e035ed",
          "md5": "c5a21f8034f1074b006e63b13ac6f7d5"
        }
      ]
    }
  ]
}
