{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "apkzlib",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "apkzlib-7.0.2.jar",
          "url": "apkzlib-7.0.2.jar",
          "size": 202778,
          "sha512": "8bbc2629aac9b640c306b97129ac384591eb339c1c5c7bbbc7ab38cdb5bdfbe94aae145b08612a2bc81354a18f036ade53d281b46cb4e48546b94e2679525997",
          "sha256": "d84efdc07ca5116395eff17f3a203e35b4d4b3d095d872a94939eff7c14434c0",
          "sha1": "6be75056a5cafbc6fd81986cfb078a9f9d1b893e",
          "md5": "aaca30b1e18885c6073b07deedfb430b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "apkzlib-7.0.2.jar",
          "url": "apkzlib-7.0.2.jar",
          "size": 202778,
          "sha512": "8bbc2629aac9b640c306b97129ac384591eb339c1c5c7bbbc7ab38cdb5bdfbe94aae145b08612a2bc81354a18f036ade53d281b46cb4e48546b94e2679525997",
          "sha256": "d84efdc07ca5116395eff17f3a203e35b4d4b3d095d872a94939eff7c14434c0",
          "sha1": "6be75056a5cafbc6fd81986cfb078a9f9d1b893e",
          "md5": "aaca30b1e18885c6073b07deedfb430b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.2-javadoc.jar",
          "url": "apkzlib-7.0.2-javadoc.jar",
          "size": 699285,
          "sha512": "1fb688ee3d1c08573c35bc58ab39080a9e8dbf376786df734411685bdab6cdcc3235c55b0d893f8b8a42c75380eb28839fa9eb544f41dd415a1287392b95e2d4",
          "sha256": "7dd337f6c7c0aa806cb247a22012d72a410f967ca653c61dd032833f84b77066",
          "sha1": "083530f6077d70e860f51aa30204fee77cbc32ed",
          "md5": "aeebe5812092fed254a9e919afea09e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apkzlib-7.0.2-sources.jar",
          "url": "apkzlib-7.0.2-sources.jar",
          "size": 175631,
          "sha512": "78350d3385bd7b2a0c8bd57c4c73ece730374d3dc57d2732ecb162473da24dd769994ae55e2900255f3f0e7856ba5747eb2fa537ddbb8eff5660ef2cd9847053",
          "sha256": "6e254745afb50381875eeba0dfeaca33f1177bda39668f845ee8249310e42f32",
          "sha1": "63eecb57bc7dedfb744cca5bdaa5fbd3fc140af2",
          "md5": "93a7f891b5be5c85a66a56b003ed2b30"
        }
      ]
    }
  ]
}
