{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "koin-android",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5nymvejb7vgjtoflzdblcoqigy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "koin-android-3.0.1.aar",
          "url": "koin-android-3.0.1.aar",
          "size": 113713,
          "sha512": "52d1c94c7487a52c46f11a736739efeda30a196d999097ab4acb1462ab40b1decfe4bcfe3b3f681c8ab4923668388763b60f2a7afe09dd4d8732238740d67747",
          "sha256": "b27fb869d3e07be7c38571b194be971f77cd074532d191739e9053aaa0be5b1a",
          "sha1": "b4d259e06ba5da2813669a09a46ff277f3c333d2",
          "md5": "78db3026edcfa75507a650f432894f00"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "koin-android-3.0.1.aar",
          "url": "koin-android-3.0.1.aar",
          "size": 113713,
          "sha512": "52d1c94c7487a52c46f11a736739efeda30a196d999097ab4acb1462ab40b1decfe4bcfe3b3f681c8ab4923668388763b60f2a7afe09dd4d8732238740d67747",
          "sha256": "b27fb869d3e07be7c38571b194be971f77cd074532d191739e9053aaa0be5b1a",
          "sha1": "b4d259e06ba5da2813669a09a46ff277f3c333d2",
          "md5": "78db3026edcfa75507a650f432894f00"
        }
      ]
    }
  ]
}
