{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-common",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "databinding-common-7.0.2.jar",
          "url": "databinding-common-7.0.2.jar",
          "size": 16103,
          "sha512": "bdfd623f5a9bf41676aa21d675dea135031757040471c41276ef0da926eda9211a937311488df89ef7673c6d2fe3bc491ad2c045d2f07e3c668b61499ba6cdd2",
          "sha256": "9b3b995587fe92c3e41569ea508d9b86b9a7c319ec6e71ac94023074ff898100",
          "sha1": "c604c89b40fc98b2c4f7152119e79c62d498cc38",
          "md5": "17a3693a825097bbf676ee42b1dfd5e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.2.jar",
          "url": "databinding-common-7.0.2.jar",
          "size": 16103,
          "sha512": "bdfd623f5a9bf41676aa21d675dea135031757040471c41276ef0da926eda9211a937311488df89ef7673c6d2fe3bc491ad2c045d2f07e3c668b61499ba6cdd2",
          "sha256": "9b3b995587fe92c3e41569ea508d9b86b9a7c319ec6e71ac94023074ff898100",
          "sha1": "c604c89b40fc98b2c4f7152119e79c62d498cc38",
          "md5": "17a3693a825097bbf676ee42b1dfd5e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.2-javadoc.jar",
          "url": "databinding-common-7.0.2-javadoc.jar",
          "size": 451434,
          "sha512": "4dba903cbe33501b851ca40e8d986e36e8fc7577734c3ab92a3e778c3fa94eedc0f37672000cd529a001f5ff003369279cf9f3eeb5af20cb908a9a56f1409806",
          "sha256": "4ed5e2c473434800e1552eb5b7eb58d4efa53ec657b689a8569c981031bbdf09",
          "sha1": "9b370fa3732199c2564df7f22bd43ba207c3ab77",
          "md5": "a73b07da0d26630c861f9ac727383d16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.2-sources.jar",
          "url": "databinding-common-7.0.2-sources.jar",
          "size": 45950,
          "sha512": "5e25e2ada3c72beccf285baccc9f9063249382a5646502f0f32d9aefa3a0b08c9a2570543320b3a4ddf4dc7a6c1aaefb286f87f271b7c36fc8bc6f689566aeee",
          "sha256": "6bc35538371c913f7c1d7c74ea4ad04028149b2124c3e856b37f48fcf6dda704",
          "sha1": "a617f1778019041607f98729be3ae69c173e3121",
          "md5": "15bcf8edc3ae81c5cd675ec45085e26f"
        }
      ]
    }
  ]
}
