{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-7.0.2.jar",
          "url": "aaptcompiler-7.0.2.jar",
          "size": 492003,
          "sha512": "3434cfff9b8f229acf92ef34fd98dd2835727a4bd5e9b16c2d6d067a378de7a45a24c1a12163672a88f52496d2ba6b357a1cfad1d738bc8a44e63f57a18732b1",
          "sha256": "837319fd7e826c13448d9f00fe1348ad9bbcbe18cd7eb3de4393529ffecbc45a",
          "sha1": "4ae043cc3bdc70b122347d2a950254499c4c4c3d",
          "md5": "53189d4ac789e63961f885ad00c126d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "7.0.2-7396180"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-7.0.2.jar",
          "url": "aaptcompiler-7.0.2.jar",
          "size": 492003,
          "sha512": "3434cfff9b8f229acf92ef34fd98dd2835727a4bd5e9b16c2d6d067a378de7a45a24c1a12163672a88f52496d2ba6b357a1cfad1d738bc8a44e63f57a18732b1",
          "sha256": "837319fd7e826c13448d9f00fe1348ad9bbcbe18cd7eb3de4393529ffecbc45a",
          "sha1": "4ae043cc3bdc70b122347d2a950254499c4c4c3d",
          "md5": "53189d4ac789e63961f885ad00c126d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-7.0.2-javadoc.jar",
          "url": "aaptcompiler-7.0.2-javadoc.jar",
          "size": 393910,
          "sha512": "5df7e00c6937c8ed435deabc9ce0db743ab5ef22709007bd18e374b5d2bdd13cde4fc8e268f3fb80c1a91456614e32f6ac0a3fc003554745c496b6859633f0a2",
          "sha256": "bd38c576ae12dc66762652effbb6015e982c452a0bb789b5ee0bc292f7ecca01",
          "sha1": "19d4f064bead7071d6df5b9f694c9aa5aaef9059",
          "md5": "1b22b6fa33b338d3940fd88dd470bc7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-7.0.2-sources.jar",
          "url": "aaptcompiler-7.0.2-sources.jar",
          "size": 149686,
          "sha512": "ab0adde90d79cf043e910b8345e66e49dac91f045d75222796a5a8b785f9ad005377350daebf3aaa2200595ece305b0dcafd9e69485c32e25d948e1ae06edfe8",
          "sha256": "5f8a5c4c6ff53e508fe3982370400e46ed3cd99b736ce99da9441a190f360ca3",
          "sha1": "a784f2c5e55178b7006dd8a82af8f59886b8d5cb",
          "md5": "ab1d1828b2f249945911dcc139bb717c"
        }
      ]
    }
  ]
}
