{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-compiler-common",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "databinding-compiler-common-7.0.2.jar",
          "url": "databinding-compiler-common-7.0.2.jar",
          "size": 498761,
          "sha512": "1cdce121fe34853ff61ddbe176400108776b9d9a897cda490f676d46359c1b0bf69009989cccd591d6411d983ae7f020a3f2e6218d682a19d4027fac702f70cf",
          "sha256": "a3f55b2539cec3e43c1936e09db2e4bd6b639027f4f5ebf87740f1b3642f9d4f",
          "sha1": "6d5ca0ebc440ab0f90bbe45434a8374dbbcd9267",
          "md5": "19f84a5c6f3b494a6222e2ce5fa00048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.5.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta09"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-compiler-common-7.0.2.jar",
          "url": "databinding-compiler-common-7.0.2.jar",
          "size": 498761,
          "sha512": "1cdce121fe34853ff61ddbe176400108776b9d9a897cda490f676d46359c1b0bf69009989cccd591d6411d983ae7f020a3f2e6218d682a19d4027fac702f70cf",
          "sha256": "a3f55b2539cec3e43c1936e09db2e4bd6b639027f4f5ebf87740f1b3642f9d4f",
          "sha1": "6d5ca0ebc440ab0f90bbe45434a8374dbbcd9267",
          "md5": "19f84a5c6f3b494a6222e2ce5fa00048"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-7.0.2-javadoc.jar",
          "url": "databinding-compiler-common-7.0.2-javadoc.jar",
          "size": 836567,
          "sha512": "0daac2236f6179d2cb42e56a20fd27a7c438ddbe17b61397155b7751974cab11b98e32c19b787681acd981d57a98296e142f9879c786229770e2cb371164581b",
          "sha256": "56674129a4a7446dee9e5a71696341330f68f8b16671a3c05613186c6e938076",
          "sha1": "512be8d2c3abe3ed16c3889e9ebe140d329325fa",
          "md5": "262f07a98ee71e0f106f0d51b94ae063"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-compiler-common-7.0.2-sources.jar",
          "url": "databinding-compiler-common-7.0.2-sources.jar",
          "size": 199162,
          "sha512": "c27b119884f6c8fd40de9cff05e1b4e9f4a23304079bd0631a97a2d20883f8ff3de721e3e80b7de8533cabd6fa082bc3986bd1c7eec132993de38d70b67992bb",
          "sha256": "90ca6cf06de4db923170bbb3070d87d15ac168477283769bd72b396e31fbd278",
          "sha1": "99c0af539d79fa0930c61ba8d3cb3d11a4a820c0",
          "md5": "bb3a46844bbaac3c50161bece830cb9e"
        }
      ]
    }
  ]
}
