{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7116490"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.3.0.aar",
          "url": "fragment-ktx-1.3.0.aar",
          "size": 14644,
          "sha512": "c55f757c6856ff3af7820cd132857659d24ed92369f44ad4ce3c5e75dc4c6d61bd573a5893aeabf6dd8c8d13ce7b026ea7e5bc5b3b0302534b291638f8afcb59",
          "sha256": "57661e76ea1e6cd41bb76aba87bf73df39426a758b628a6ce2d71a6810d96658",
          "sha1": "d0965bbada332f6d62cf9d503c662d1f77b01783",
          "md5": "ebdf261610fb372b6b9543ba69a32555"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.3.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.3.0.aar",
          "url": "fragment-ktx-1.3.0.aar",
          "size": 14644,
          "sha512": "c55f757c6856ff3af7820cd132857659d24ed92369f44ad4ce3c5e75dc4c6d61bd573a5893aeabf6dd8c8d13ce7b026ea7e5bc5b3b0302534b291638f8afcb59",
          "sha256": "57661e76ea1e6cd41bb76aba87bf73df39426a758b628a6ce2d71a6810d96658",
          "sha1": "d0965bbada332f6d62cf9d503c662d1f77b01783",
          "md5": "ebdf261610fb372b6b9543ba69a32555"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-ktx-1.3.0-sources.jar",
          "url": "fragment-ktx-1.3.0-sources.jar",
          "size": 6158,
          "sha512": "476292abaed3998c04465525063852d295c5abe1df6bd19dd546c5356dbf9f9131a21d9704c7eb9a11231de7546311fc4c20dfb8cbab99634128fa44ff705670",
          "sha256": "8d2f635ee0969b1709aaaf4681ad2c857a95ade73736e5900f7b0809518794bd",
          "sha1": "b64a27a0cae3596d8bfba86d5fdb427c38b5a7ed",
          "md5": "66eec5468ecf2711c475d79392354ed3"
        }
      ]
    }
  ]
}
