{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7104547"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0.aar",
          "size": 13759,
          "sha512": "08a3802009ebf335b553d6ad3edb20158c22d7284d1293505932df6bc819585ab4f422e1b16ad64905e764ebcda0adba096357d34aabc7d303f8a774ea201bb6",
          "sha256": "6598e65b66f6011d43d5d9675a37338e50741f31dda15863514cfffab035b9ee",
          "sha1": "15bdff6995f4c429f84711b57eaad368b40a0625",
          "md5": "e4ea9c0044171c04f6120c0c7c2e1917"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0.aar",
          "url": "lifecycle-livedata-core-ktx-2.3.0.aar",
          "size": 13759,
          "sha512": "08a3802009ebf335b553d6ad3edb20158c22d7284d1293505932df6bc819585ab4f422e1b16ad64905e764ebcda0adba096357d34aabc7d303f8a774ea201bb6",
          "sha256": "6598e65b66f6011d43d5d9675a37338e50741f31dda15863514cfffab035b9ee",
          "sha1": "15bdff6995f4c429f84711b57eaad368b40a0625",
          "md5": "e4ea9c0044171c04f6120c0c7c2e1917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-ktx-2.3.0-sources.jar",
          "url": "lifecycle-livedata-core-ktx-2.3.0-sources.jar",
          "size": 1631,
          "sha512": "aec27370748b879276405755e63a377e08307bfe2f370687ee18fa5c43cb5e203fe5e3bcc9cda40390c872bf279e96bc2bae2f0a9e2ee631f861b2ad0e54c0ae",
          "sha256": "b7a2a7c66a58440b0ba30c68abe17074836f217123fb6ea728279834641a7c77",
          "sha1": "0ec507705520b7ddccce7da52bbf5abd9ecd1808",
          "md5": "c552138cfc58a3f4d73c8acbb66e4a86"
        }
      ]
    }
  ]
}
